"""Add_closedat_column_to_task_model

Revision ID: 62b73a705ab8
Revises: a6cc7a186406
Create Date: 2025-11-30 12:31:39.375893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b73a705ab8'
down_revision: Union[str, None] = 'a6cc7a186406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'closed_at')
    # ### end Alembic commands ###
